### ISSUE TITLE
Response locked, mismatch number of responses and actual correct responses, 

### ISSUE THREAD

**Issue by ArthurNguyen** [mscheltienne/eeg-flow#34]
https://github.com/mscheltienne/eeg-flow/blob/37f3e597c1f6511e7ccb9c17b63de0a6089fe8e6/eeg_flow/tasks/epochs_evoked.py#L229

Hello, 
Dans un exemple ou un enregistrement contient des falses alarms (le participant a appuyé alors qu'il n'aurait pas du), 
- metadata_reponse["event_name"] va contenir strictement les evenements "responses" dont les faut
- metadata_reponse["response_time"] ne contient que les bonnes reponses (== Hits)
Donc il y aura par exemple 36 event_name et 35 response_time

Tu arriverais a voir comment filtrer facilement la premiere partie pour retirer ces mauvaises reponses?
Merci

Arthur

https://we.tl/t-Pisv83JNjC

**Comment by mscheltienne** [comment]
Appreciate the file :)

FYI, minimally reproducible example:

```
from mne.io import read_raw_fif

from eeg_flow.tasks.epochs_evoked import _create_epochs_evoked_and_behavioral_metadata


fname = (
    r"/home/scheltie/Downloads/sub-P02-G2_task-oddball_run-2_step7_preprocessed_raw.fif"
)
raw = read_raw_fif(fname, preload=True)
_create_epochs_evoked_and_behavioral_metadata(raw)
```
